
SET  @idPais = 30;
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (12, 'Acre', 'AC', 1,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (27, 'Alagoas', 'AL', 2,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (16, 'Amapá', 'AP', 1,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (13, 'Amazonas', 'AM', 1,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (29, 'Bahia', 'BA', 2,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (23, 'Ceará', 'CE', 2,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (53, 'Distrito Federal', 'DF', 5,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (32, 'Espírito Santo', 'ES', 3,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (52, 'Goiás', 'GO', 5,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (21, 'Maranhão', 'MA', 2,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (51, 'Mato Grosso', 'MT', 5,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (50, 'Mato Grosso do Sul', 'MS', 5,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (31, 'Minas Gerais', 'MG', 3,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (15, 'Pará', 'PA', 1,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (25, 'Paraíba', 'PB', 2,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (41, 'Paraná', 'PR', 4,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (26, 'Pernambuco', 'PE', 2,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (22, 'Piauí', 'PI', 2,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (33, 'Rio de Janeiro', 'RJ', 3,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (24, 'Rio Grande do Norte', 'RN', 2,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (43, 'Rio Grande do Sul', 'RS', 4,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (11, 'Rondônia', 'RO', 1,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (14, 'Roraima', 'RR', 1,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (42, 'Santa Catarina', 'SC', 4,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (35, 'São Paulo', 'SP', 3,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (28, 'Sergipe', 'SE', 2,@idPais);
Insert into Estado (CodigoUf, Nome, Uf, Regiao_id, Pais_id) values (17, 'Tocantins', 'TO', 1,@idPais);