INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('DIVERSOS','DIVERSOS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('JOHNSON&JOHNSON','JOHNSON&JOHNSON', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MUNDIAL','MUNDIAL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('KERRY','KERRY', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('BATAVO','BATAVO', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PARMALAT','PARMALAT', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('DA VINCI','DA VINCI', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CAFE PESSEGUEIRO','CAFE PESSEGUEIRO', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MINALBA','MINALBA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PERRIER','PERRIER', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('NESTLE','NESTLE', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('GAROTO','GAROTO', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CALLEBAUT','CALLEBAUT', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MELHORAMENTOS','MELHORAMENTOS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('SCHMIDT','SCHMIDT', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('NADIR FIGUEIREDO','NADIR FIGUEIREDO', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('BUNGE','BUNGE', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('TRAMONTINA','TRAMONTINA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CISPER','CISPER', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('BELA VISTA','BELA VISTA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('STOCK','STOCK', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('GRANTS','GRANTS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('OSBORNE','OSBORNE', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MONTILLA','MONTILLA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('ILE DE FRANCE','ILE DE FRANCE', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('DR.OETKER','DR.OETKER', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('FABER CASTEL','FABER CASTEL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('BIC','BIC', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CHINES','CHINES', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('UZ,','UZ,', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CLINK','CLINK', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('INOVA','INOVA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('ANYCOLOR','ANYCOLOR', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('RISQUE','RISQUE', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('OI','OI', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('NEW BABY','NEW BABY', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('HAVAIANAS SERRANA','HAVAIANAS SERRANA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('HAVAIANAS ORIGINAL','HAVAIANAS ORIGINAL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('EMBALAGENS PRESENTE','EMBALAGENS PRESENTE', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PORTA LAPIS','PORTA LAPIS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MOCHILAS','MOCHILAS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('ARAMADOS/INOX','ARAMADOS/INOX', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('LIXEIRA INOX','LIXEIRA INOX', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('TIME','TIME', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CHAVEIROS','CHAVEIROS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('COLAS','COLAS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MEIAS','MEIAS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CABELO','CABELO', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('COSTURA','COSTURA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('ISQUEIROS','ISQUEIROS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CHIPS','CHIPS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('JOGOS/DIVERSAO','JOGOS/DIVERSAO', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('SOMBRINHAS/GUARDA CHUVAS','SOMBRINHAS/GUARDA CHUVAS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('TINTOL','TINTOL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('KTS DIVEERSOS','KTS DIVEERSOS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('BIC','BIC', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PANASONIC','PANASONIC', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('ALFACEL','ALFACEL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('EVEREDY','EVEREDY', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('THREE BOND','THREE BOND', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('ALMA SUPER','ALMA SUPER', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('TEK BOND 793','TEK BOND 793', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('AGUIA','AGUIA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CORRENTE','CORRENTE', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('NEW BABY','NEW BABY', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('NEW BABY','NEW BABY', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MOMO','MOMO', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MOMO','MOMO', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('FROZEN','FROZEN', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('FLAMINCO','FLAMINCO', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('UNICORNIO','UNICORNIO', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('AL UNICORNIO E OUTROS','AL UNICORNIO E OUTROS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('FWB','FWB', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CASSITA','CASSITA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('FWB','FWB', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CASITA','CASITA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PLASTICO','PLASTICO', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PANAMBY PLASTICOS','PANAMBY PLASTICOS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PLASDURAN','PLASDURAN', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PLASTISUL','PLASTISUL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PLASTISUL','PLASTISUL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PLASTISUL','PLASTISUL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('LOLLY','LOLLY', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CONDOR','CONDOR', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('SABOR DE FESTA','SABOR DE FESTA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PIXOXO','PIXOXO', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MANDALA','MANDALA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('WELLMIX','WELLMIX', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('KE HOME','KE HOME', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('STARHOUSE','STARHOUSE', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MINAS RIO','MINAS RIO', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('WESTERN','WESTERN', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('ORIGINAL LINE','ORIGINAL LINE', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('FWB','FWB', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('KEITA','KEITA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MAXXIMO','MAXXIMO', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('LEVE MAIS','LEVE MAIS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('DM COOKER','DM COOKER', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('WINCY','WINCY', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('TOP RIO','TOP RIO', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MONALIZA','MONALIZA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('UNICASA','UNICASA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CLINK','CLINK', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PLASÚTIL','PLASÚTIL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('BARCELONA','BARCELONA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('SPLANDBALL','SPLANDBALL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('AJAX','AJAX', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('LIG BRIN','LIG BRIN', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MANANCIAL','MANANCIAL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('YAZI','YAZI', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('YCPB','YCPB', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('INJETEMP','INJETEMP', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('FRATELLI','FRATELLI', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CORTEX','CORTEX', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('UNI HOME','UNI HOME', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('UYJ','UYJ', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('TOP HOUSE','TOP HOUSE', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('KITCHEN','KITCHEN', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('123 UTIL','123 UTIL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('123 UTIL','123 UTIL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('WINCY','WINCY', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('SIMONAGGIO','SIMONAGGIO', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('SQ','SQ', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('RIOMASTER','RIOMASTER', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('STATRHOUSE','STATRHOUSE', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('IDEA','IDEA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('GOLLER','GOLLER', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CELUZ','CELUZ', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('FORLUX','FORLUX', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('NATICON','NATICON', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('JETCON','JETCON', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('ORTHO PAUHER','ORTHO PAUHER', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MAXMIDIA','MAXMIDIA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('LEITEMING','LEITEMING', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('COLONIAL','COLONIAL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('NIQUELART','NIQUELART', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('HOGAR UTIL','HOGAR UTIL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PRATIBELLA','PRATIBELLA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('DINAMICA DO BRASIL','DINAMICA DO BRASIL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('STAINLESS','STAINLESS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CASAAMBIENTE','CASAAMBIENTE', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('HOME MANIA','HOME MANIA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('SPLAND','SPLAND', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('AUIYI','AUIYI', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('VIMAS','VIMAS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('FORONI','FORONI', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('NITRON','NITRON', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('VOLK DO BRASIL','VOLK DO BRASIL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('SECALUX','SECALUX', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MILPLASTIC','MILPLASTIC', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('NEW','NEW', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('HR PORCELANAS','HR PORCELANAS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('JOCAR OFFICE','JOCAR OFFICE', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('POSTIT','POSTIT', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('EURIBEL','EURIBEL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PLASMARC','PLASMARC', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MARBEL','MARBEL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('ERCA PLAST','ERCA PLAST', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('COPAG','COPAG', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MERCUR','MERCUR', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MULTILASER','MULTILASER', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('IOB ARTEPINUS','IOB ARTEPINUS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('BIG BOY','BIG BOY', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('TOYS','TOYS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('OMOTCHA','OMOTCHA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CRIATIVE KIDS','CRIATIVE KIDS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MAMITA','MAMITA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('GOLD FINGER','GOLD FINGER', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('RUBY ROSE','RUBY ROSE', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('SHINES','SHINES', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('SAFIRA','SAFIRA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('EVOK','EVOK', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('COLOR POP','COLOR POP', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('ACGUA LIPS','ACGUA LIPS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('DISCOTECH','DISCOTECH', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('FENZZA','FENZZA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('SABRINA SATO','SABRINA SATO', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MEIUSTAR','MEIUSTAR', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PUFF','PUFF', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MILK','MILK', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('KRONOS','KRONOS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PAIS E FILHOS','PAIS E FILHOS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('KENDY','KENDY', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('DIVPLAST','DIVPLAST', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('GOAL KIDS','GOAL KIDS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('7896885202850','7896885202850', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('BABY DIDÁTICO ','BABY DIDÁTICO ', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('DR BABY','DR BABY', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('TOYS E TOYS','TOYS E TOYS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PICA  PAU','PICA  PAU', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('LOL','LOL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MERCOTOYS','MERCOTOYS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('ERCA PLAST','ERCA PLAST', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('ACRILIX','ACRILIX', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('COPAG','COPAG', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PLATIC','PLATIC', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('TRITEC','TRITEC', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('VOLARE','VOLARE', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MSR','MSR', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('JAGUAR','JAGUAR', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CORTEX','CORTEX', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('JBL','JBL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('SUMEXR','SUMEXR', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('DATERRA','DATERRA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PHILCO','PHILCO', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('UNCOMMON','UNCOMMON', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MECHANICAL PENCIL','MECHANICAL PENCIL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MERCUR','MERCUR', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('KOALA','KOALA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('ALMAFLEX','ALMAFLEX', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('REAL SEDA','REAL SEDA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('WINNER','WINNER', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('TILIBRA','TILIBRA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('JANDAIA','JANDAIA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MÁXIMA','MÁXIMA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('STARBEAUTY','STARBEAUTY', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('TRIM','TRIM', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('TRIM','TRIM', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('JAGUAR','JAGUAR', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('NIQUELART','NIQUELART', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('ARQUIPLAST','ARQUIPLAST', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('ARQUIPLAST','ARQUIPLAST', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PANELUX','PANELUX', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('FNG','FNG', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CIV','CIV', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('ALUMINIO OLIVEIRA','ALUMINIO OLIVEIRA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PLASMONT','PLASMONT', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('UZ','UZ', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('INPLAST','INPLAST', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('NADIR','NADIR', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('KAVEH','KAVEH', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CLASS','CLASS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('AIRPROOF POT','AIRPROOF POT', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('KLASSIKGLAS','KLASSIKGLAS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('VITRIZI','VITRIZI', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('LYOR','LYOR', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('GRAFONS','GRAFONS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('YIN''S','YIN''S', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CLASSE','CLASSE', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('IARA','IARA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('HOOPSON','HOOPSON', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('LAPISPEL','LAPISPEL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('SHENG','SHENG', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('JOGAR OFFICE','JOGAR OFFICE', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('INTERPONTE ','INTERPONTE ', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MAPED','MAPED', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CIS','CIS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('BIC','BIC', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('COMPACTOR','COMPACTOR', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MERCUR','MERCUR', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('APLICOLA','APLICOLA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('ACRILEX','ACRILEX', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MAGIX','MAGIX', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('UTIGUTI','UTIGUTI', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('INVICTA','INVICTA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('EGLE','EGLE', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('COPAG ','COPAG ', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('RAYOVAC','RAYOVAC', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PILOT','PILOT', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('BESTFER','BESTFER', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('SELENE','SELENE', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('TRIFIL','TRIFIL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('DERBY','DERBY', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('TORP','TORP', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('STREETMAN','STREETMAN', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CHAMEQUINHO','CHAMEQUINHO', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('SÃO DOMINGOS','SÃO DOMINGOS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('NEW MAGIC','NEW MAGIC', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('DELTA','DELTA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('WALEU','WALEU', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('DELLO','DELLO', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('VOLORIZI','VOLORIZI', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('COLORIZI','COLORIZI', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('DATERRA','DATERRA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PRIME','PRIME', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('DRIMA','DRIMA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('TREE BOND','TREE BOND', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('ELGIN','ELGIN', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('ALFACEL','ALFACEL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MAXDAY','MAXDAY', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('H''MASTON','H''MASTON', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('SUMEXR','SUMEXR', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('SAMSUNG','SAMSUNG', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('IDEAL','IDEAL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CLOSEUP','CLOSEUP', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('HOTWHEEL','HOTWHEEL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('WELLMIX','WELLMIX', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('RUTMAR','RUTMAR', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MARTINOS','MARTINOS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('WIRELESS','WIRELESS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('RUBY ROSE','RUBY ROSE', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('BELA FEMME','BELA FEMME', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('SABOR DE FESTA','SABOR DE FESTA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('ART TELAS','ART TELAS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('APLICOLA','APLICOLA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('UTI GUTI','UTI GUTI', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('FIT PEL','FIT PEL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('STEFFANS','STEFFANS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CARMEN STEFFENS','CARMEN STEFFENS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('HAVAIANAS 01','HAVAIANAS 01', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('TROPICALIA','TROPICALIA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('ANALENI','ANALENI', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('KAVEH','KAVEH', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('PILOT','PILOT', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('DELTA','DELTA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('LANTU','LANTU', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('KAZ','KAZ', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MAXDAY','MAXDAY', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('H''MASTON','H''MASTON', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('WIRELESS','WIRELESS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('LEO&LEO','LEO&LEO', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('SKALA','SKALA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('TABU','TABU', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('HERBISSIMO','HERBISSIMO', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('ONLY','ONLY', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('DARMA','DARMA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('SANTA CLARA','SANTA CLARA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('LUIZA','LUIZA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CONDOR','CONDOR', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('LANDHS','LANDHS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('CORTEX','CORTEX', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('TRIS','TRIS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('MIUNDO CASA','MIUNDO CASA', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('NATAL','NATAL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('BEE TOYS','BEE TOYS', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('NEW BORN','NEW BORN', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('HMASTON','HMASTON', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('EBACI','EBACI', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('SAN DIEGO','SAN DIEGO', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('VIEL','VIEL', '1') ;
INSERT INTO `Fabricante` (`Nome`, `Descricao`, `Ativo`) VALUES ('ALUSOL','ALUSOL', '1') ;