INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('DIVERSOS','DIVERSOS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('BEBIDAS','BEBIDAS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('ALIMENTOS','ALIMENTOS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('MATERIAL DE LIMPEZA','MATERIAL DE LIMPEZA', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('SECOS','SECOS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('HORTI-FRUTI','HORTI-FRUTI', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('LATICINIOS','LATICINIOS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('PROCESSADOS','PROCESSADOS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('PATISSERIE','PATISSERIE', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('VIENNOISERIE','VIENNOISERIE', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('PETITS-FOURS','PETITS-FOURS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('CHOCOLAT','CHOCOLAT', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('CAFE','CAFE', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('BEBIDAS DE CAFE','BEBIDAS DE CAFE', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('OUTRAS BEBIDAS - CARDAPIO','OUTRAS BEBIDAS - CARDAPIO', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('INSUMOS INDIRETOS','INSUMOS INDIRETOS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('EMBUTIDOS','EMBUTIDOS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('CARNES','CARNES', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('ENCOMENDAS','ENCOMENDAS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('MATERIAL ESCOLAR','MATERIAL ESCOLAR', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('BRINQUEDOS','BRINQUEDOS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('UTENSILIOS DOMESTICOS','UTENSILIOS DOMESTICOS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('ELETRONICOS E INFORMATICA','ELETRONICOS E INFORMATICA', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('COSMETICO','COSMETICO', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('RECARGA','RECARGA', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('UTENSILIOS INFANTIL','UTENSILIOS INFANTIL', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('PRDUTOS FDE BELEZA','PRDUTOS FDE BELEZA', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('PRODUTOS BANHO','PRODUTOS BANHO', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('BRINQUEDOS','BRINQUEDOS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('PAPELARIA','PAPELARIA', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('LINHA BABY','LINHA BABY', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('BELEZA','BELEZA', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('PRESENTES','PRESENTES', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('BRINQUEDOS','BRINQUEDOS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('BIJOUTEIRIA','BIJOUTEIRIA', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('CALÇADOS','CALÇADOS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('COPOS','COPOS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('XICARAS','XICARAS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('JARRAS','JARRAS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('PLASTICOS','PLASTICOS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('INFANTIL/BABY','INFANTIL/BABY', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('COPO INFANTIL','COPO INFANTIL', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('COPO INFANTIL COM ALÇA','COPO INFANTIL COM ALÇA', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('GARRAFA TERMICA','GARRAFA TERMICA', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('GARRAFA TERMICA INOX','GARRAFA TERMICA INOX', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('GARRAFA SQUEEZE','GARRAFA SQUEEZE', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('LOLLY XUQUINHA','LOLLY XUQUINHA', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('FESTAS','FESTAS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('LOUÇAS','LOUÇAS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('COZINHA','COZINHA', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('LIMPEZA','LIMPEZA', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('JOGOS DIVERSAO','JOGOS DIVERSAO', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('ELETRONICOS','ELETRONICOS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('PEDAGOGICO','PEDAGOGICO', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('ILUNINAÇAO','ILUNINAÇAO', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('SOM','SOM', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('PORTA CDS','PORTA CDS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('NATAL','NATAL', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('BARBEAR','BARBEAR', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('CALCADOS','CALCADOS', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('ADORNO','ADORNO', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('NATAL','NATAL', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('BRINQUEDO','BRINQUEDO', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('7824257015883','7824257015883', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('HIGIENE PESSOAL ','HIGIENE PESSOAL ', '1') ;
INSERT INTO `GrupoProduto` (`Nome`, `Descricao`, `Ativo`) VALUES ('BANHO','BANHO', '1') ;